pipeline {
  agent any
  parameters {
    string(name: 'AWS_ACCOUNT_ID', defaultValue: '464868388928', description: 'AWS account id')
    string(name: 'ECR_REPO', defaultValue: 'dynamodb-demo', description: 'ECR repository name')
    string(name: 'CLUSTER_NAME', defaultValue: 'dynamodb-demo-cluster', description: 'ECS cluster name')
    string(name: 'SERVICE_NAME', defaultValue: 'dynamodb-demo-service', description: 'ECS service name')
    string(name: 'TASK_FAMILY', defaultValue: 'dynamodb-demo-task', description: 'ECS task family')
    string(name: 'IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag')
  }
  environment {
    AWS_REGION = "us-east-1"
    AWS_ACCOUNT_ID = "${params.AWS_ACCOUNT_ID}"
    ECR_REPO = "${params.ECR_REPO}"
    IMAGE_TAG = "${params.IMAGE_TAG}"
    CLUSTER_NAME = "${params.CLUSTER_NAME}"
    SERVICE_NAME = "${params.SERVICE_NAME}"
    TASK_FAMILY = "${params.TASK_FAMILY}"
  }
  stages {
    stage('Checkout') {
      steps { checkout scm }
    }
    stage('Build') {
      steps {
        dir('dynamodb-demo') {
          sh './mvnw -B -DskipTests package'
        }
      }
    }
    stage('Test') {
      steps {
        dir('dynamodb-demo') {
          sh './mvnw test -q'
        }
      }
    }
    stage('Build & Push Image') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'aws', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
          dir('dynamodb-demo') {
            sh "./scripts/ecr_login_and_push.sh ${AWS_ACCOUNT_ID} ${AWS_REGION} ${ECR_REPO} ${IMAGE_TAG}"
          }
        }
      }
    }
    stage('Deploy to ECS') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'aws', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
          dir('dynamodb-demo') {
            sh "./scripts/deploy_ecs.sh ${AWS_ACCOUNT_ID} ${AWS_REGION} ${CLUSTER_NAME} ${SERVICE_NAME} ${TASK_FAMILY} ${ECR_REPO} ${IMAGE_TAG}"
          }
        }
      }
    }
    stage('Monitor ECS') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'aws', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
          dir('dynamodb-demo') {
            sh 'python3 agent/ecs_monitor_agent.py --region ${AWS_REGION} --cluster ${CLUSTER_NAME} --service ${SERVICE_NAME} --audit-table AgentAudit --once'
          }
        }
      }
    }
  }
}
