spring.application.name=dynamodb-demo

app.aws.region=us-east-1
app.aws.dynamodb.endpoint=http://localhost:8000
app.aws.access-key-id=test
app.aws.secret-access-key=test
app.dynamodb.table-name=EmployeeTable